// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizServer.Models.DatabaseRelevant.Entities;

#nullable disable

namespace QuizServer.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260709200054_FixedQuestionClassQuizInfoFromFieldsToProperties")]
    partial class FixedQuestionClassQuizInfoFromFieldsToProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageContent")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MultiChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SingleChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrueFalseQuestionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MultiChoiceQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SingleChoiceQuestionId");

                    b.HasIndex("TrueFalseQuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Abstracts.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<int>("PointsWeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeLimit")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.MultiChoiceAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MultiChoiceAnswers");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.ShortTextAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShortTextAnswers");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.SingleChoiceAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SingleChoiceAnswers");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.TrueFalseAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrueFalseAnswers");
                });

            modelBuilder.Entity("QuizServer.Models.UserRelevant.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("MultiChoiceQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.ShortTextQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ShortTextQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("SingleChoiceQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("TrueFalseQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.QuestionOption", b =>
                {
                    b.HasOne("QuizServer.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("MultiChoiceQuestionId");

                    b.HasOne("QuizServer.Models.QuizRelevant.Abstracts.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizServer.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("SingleChoiceQuestionId");

                    b.HasOne("QuizServer.Models.QuizRelevant.Entities.Questions.TrueFalseQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("TrueFalseQuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Abstracts.Question", b =>
                {
                    b.HasOne("QuizServer.Models.Entities.QuizRelevant.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.TrueFalseQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
