// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizServer.Models.DatabaseRelevant.Entities;

#nullable disable

namespace QuizServer.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260709152558_AddAnswerDbSets")]
    partial class AddAnswerDbSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.CheckAnswerResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsGained")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CheckAnswerResult");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.ParticipantQuestionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnswerResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("AnswerResultId");

                    b.HasIndex("ParticipantResultId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ParticipantQuestionResults");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.ParticipantResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Place")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ParticipantResults");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageContent")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MultiChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SingleChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrueFalseQuestionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MultiChoiceQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SingleChoiceQuestionId");

                    b.HasIndex("TrueFalseQuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Abstracts.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<int>("PointsWeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeLimit")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Answer");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Answer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("QuizServer.Models.UserRelevant.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("MultiChoiceQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.ShortTextQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ShortTextQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("SingleChoiceQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("QuizServer.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("TrueFalseQuestion");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.MultiChoiceAnswer", b =>
                {
                    b.HasBaseType("QuizServer.Models.SessionRelevant.Answers.Answer");

                    b.PrimitiveCollection<string>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MultiChoiceAnswer");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.ShortTextAnswer", b =>
                {
                    b.HasBaseType("QuizServer.Models.SessionRelevant.Answers.Answer");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ShortTextAnswer");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.SingleChoiceAnswer", b =>
                {
                    b.HasBaseType("QuizServer.Models.SessionRelevant.Answers.Answer");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SingleChoiceAnswer");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Answers.TrueFalseAnswer", b =>
                {
                    b.HasBaseType("QuizServer.Models.SessionRelevant.Answers.Answer");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("TEXT");

                    b.ToTable("Answer", t =>
                        {
                            t.Property("SelectedOptionId")
                                .HasColumnName("TrueFalseAnswer_SelectedOptionId");
                        });

                    b.HasDiscriminator().HasValue("TrueFalseAnswer");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.ParticipantQuestionResult", b =>
                {
                    b.HasOne("QuizServer.Models.SessionRelevant.Answers.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizServer.Models.Entities.QuizRelevant.CheckAnswerResult", "AnswerResult")
                        .WithMany()
                        .HasForeignKey("AnswerResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizServer.Models.Entities.QuizRelevant.ParticipantResult", null)
                        .WithMany("QuestionResults")
                        .HasForeignKey("ParticipantResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizServer.Models.QuizRelevant.Abstracts.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("AnswerResult");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.ParticipantResult", b =>
                {
                    b.HasOne("QuizServer.Models.SessionRelevant.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.QuestionOption", b =>
                {
                    b.HasOne("QuizServer.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("MultiChoiceQuestionId");

                    b.HasOne("QuizServer.Models.QuizRelevant.Abstracts.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizServer.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("SingleChoiceQuestionId");

                    b.HasOne("QuizServer.Models.QuizRelevant.Entities.Questions.TrueFalseQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("TrueFalseQuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Abstracts.Question", b =>
                {
                    b.HasOne("QuizServer.Models.Entities.QuizRelevant.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizServer.Models.SessionRelevant.Participant", b =>
                {
                    b.HasOne("QuizServer.Models.UserRelevant.UserAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.ParticipantResult", b =>
                {
                    b.Navigation("QuestionResults");
                });

            modelBuilder.Entity("QuizServer.Models.Entities.QuizRelevant.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizServer.Models.QuizRelevant.Entities.Questions.TrueFalseQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
