// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizClient.Models.DatabaseRelevant.Entities;

#nullable disable

namespace QuizClient.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260709200922_FixingError")]
    partial class FixingError
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuizClient.Models.Entities.QuizRelevant.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageContent")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MultiChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SingleChoiceQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MultiChoiceQuestionId");

                    b.HasIndex("SingleChoiceQuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("QuizClient.Models.Entities.QuizRelevant.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizClient.Models.QuizRelevant.Abstracts.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<int>("PointsWeight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuizClient.Models.UserRelevant.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("QuizClient.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizClient.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("MultiChoiceQuestion");
                });

            modelBuilder.Entity("QuizClient.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizClient.Models.QuizRelevant.Abstracts.Question");

                    b.HasDiscriminator().HasValue("SingleChoiceQuestion");
                });

            modelBuilder.Entity("QuizClient.Models.Entities.QuizRelevant.QuestionOption", b =>
                {
                    b.HasOne("QuizClient.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("MultiChoiceQuestionId");

                    b.HasOne("QuizClient.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("SingleChoiceQuestionId");
                });

            modelBuilder.Entity("QuizClient.Models.QuizRelevant.Abstracts.Question", b =>
                {
                    b.HasOne("QuizClient.Models.Entities.QuizRelevant.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizClient.Models.Entities.QuizRelevant.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizClient.Models.QuizRelevant.Entities.Questions.MultiChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizClient.Models.QuizRelevant.Entities.Questions.SingleChoiceQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
